In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection  import train_test_split # divise le dataset en donnee entrainement et test
from sklearn.naive_bayes import GaussianNB # algo du naive bayes
from sklearn.metrics import accuracy_score , confusion_matrix 
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [35]:
df = pd.read_csv("iris.csv")
df.head()

   Sepal Length  Sepal Width  Petal Length  Petal Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal Length  150 non-null    float64
 1   Sepal Width   150 non-null    float64
 2   Petal Length  150 non-null    float64
 3   Petal Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [37]:
df.duplicated().sum()

1

In [38]:
X = df.drop("Species" , axis = 1)
y = df["Species"]
X

     Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [39]:
X_train, X_test ,y_train , y_test = train_test_split(X , y , test_size = 0.2)

In [40]:
X_train.shape

(120, 4)

In [41]:
X_test.shape

(30, 4)

In [42]:
y_train.shape

(120,)

In [43]:
y_test.shape

(30,)

## MIse en place de notre 1ere modele

In [44]:
# chargement de l algo
model_NB = GaussianNB()

In [45]:
# entraitenement
model_NB.fit(X_train , y_train )

GaussianNB()

In [46]:
# Prediction
y_pred = model_NB.predict(X_test)
y_pred

array(['versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'setosa', 'versicolor', 'setosa', 'setosa', 'virginica', 'setosa',
       'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'virginica', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'virginica'], dtype='<U10')

In [47]:
score =  cross_val_score(model_NB , X , y , cv = 5)
score.mean()

0.9533333333333334

In [48]:
X_new = [[3 , 5 , 4 ,2]]
model_NB.predict(X_new)

C:\Users\TBE\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array(['virginica'], dtype='<U10')

In [49]:
# evaluation de la performance du modele
performance = accuracy_score (y_test , y_pred)
performance

0.9

In [50]:
error = 1 - performance
error

0.09999999999999998

In [51]:
confusion_matrix(y_test , y_pred)

array([[14,  0,  0],
       [ 0,  6,  2],
       [ 0,  1,  7]], dtype=int64)

In [56]:
with open("model_NB.pkl", "wb") as f:
    pickle.dump(model_NB, f)

In [28]:
model_KNN = KNeighborsClassifier(n_neighbors = 4).fit(X_train , y_train )

In [29]:
y_knn_pred = model_KNN.predict(X_test)

In [30]:
accuracy_score(y_test , y_knn_pred )

0.9666666666666667

In [31]:
scores=[]
for k in range(1,30): 
    model_KNN = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train) 
    y_pred_knn=model_KNN.predict(X_test)
    print('Accuracy for k=',k,'is:',round(accuracy_score(y_pred,y_test),2))

scores.append(round(accuracy_score(y_pred,y_test),2))

Accuracy for k= 1 is: 0.93
Accuracy for k= 2 is: 0.93
Accuracy for k= 3 is: 0.93
Accuracy for k= 4 is: 0.93
Accuracy for k= 5 is: 0.93
Accuracy for k= 6 is: 0.93
Accuracy for k= 7 is: 0.93
Accuracy for k= 8 is: 0.93
Accuracy for k= 9 is: 0.93
Accuracy for k= 10 is: 0.93
Accuracy for k= 11 is: 0.93
Accuracy for k= 12 is: 0.93
Accuracy for k= 13 is: 0.93
Accuracy for k= 14 is: 0.93
Accuracy for k= 15 is: 0.93
Accuracy for k= 16 is: 0.93
Accuracy for k= 17 is: 0.93
Accuracy for k= 18 is: 0.93
Accuracy for k= 19 is: 0.93
Accuracy for k= 20 is: 0.93
Accuracy for k= 21 is: 0.93
Accuracy for k= 22 is: 0.93
Accuracy for k= 23 is: 0.93
Accuracy for k= 24 is: 0.93
Accuracy for k= 25 is: 0.93
Accuracy for k= 26 is: 0.93
Accuracy for k= 27 is: 0.93
Accuracy for k= 28 is: 0.93
Accuracy for k= 29 is: 0.93